version: '3.9'
services:
  chatty_postgres:
    image: postgres:16.3-alpine
    container_name: chatty_postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 112233
      POSTGRES_DB: household
  chatty_mongo:
    image: mongo:latest
    container_name: chatty_mongo
    ports:
      - '27027:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 112233
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  chatty_redis:
    image: redis/redis-stack:7.4.0-v0
    container_name: chatty_redis
    hostname: redis
    restart: always
    ports:
      - '6543:6379'
